name: layouts_-_full_width
timestamp: 1562905228
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1457353897
positions: {  }
sections:
  top: Top
  navigation: Navigation
  slideshow: Slideshow
  above: Above
  showcase: Showcase
  utility: Utility
  feature: Feature
  sidebar: Sidebar
  mainbar: Mainbar
  expanded: Expanded
  extension: Extension
  bottom: Bottom
  copyright: Copyright
  header: Header
  aside: Aside
  footer: Footer
  offcanvas: Offcanvas
particles:
  simplecontent:
    simplecontent-7561: 'Fullwidth Example'
  custom:
    custom-8235: 'H2 Heading'
  messages:
    system-messages-1344: 'System Messages'
  logo:
    logo-7043: Logo
  menu:
    menu-6172: Menu
  shoppingcart:
    shoppingcart-1669: 'Shopping Cart'
  simplemenu:
    simplemenu-4925: 'Bottom Menu'
  branding:
    branding-8049: Branding
  mobile-menu:
    mobile-menu-9584: Mobile-menu
inherit:
  default:
    top: top
    navigation: navigation
    header: header
    above: above
    showcase: showcase
    utility: utility
    feature: feature
    expanded: expanded
    extension: extension
    bottom: bottom
    footer: footer
    copyright: copyright
    offcanvas: offcanvas
    system-messages-1344: system-messages-9828
    logo-7043: logo-5992
    menu-6172: menu-4196
    shoppingcart-1669: shoppingcart-5200
    simplemenu-4925: simplemenu-6826
    branding-8049: branding-9192
    mobile-menu-9584: mobile-menu-7951
