name: layouts_-_right_sidebar
timestamp: 1562905228
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1457353897
positions: {  }
sections:
  top: Top
  navigation: Navigation
  slideshow: Slideshow
  above: Above
  showcase: Showcase
  utility: Utility
  feature: Feature
  mainbar: Mainbar
  sidebar: Sidebar
  expanded: Expanded
  extension: Extension
  bottom: Bottom
  copyright: Copyright
  header: Header
  footer: Footer
  offcanvas: Offcanvas
particles:
  simplecontent:
    simplecontent-7561: 'Right Sidebar Example'
  custom:
    custom-8235: 'H2 Heading'
    custom-7406: 'Right Sidebar'
    custom-9224: 'Flexible Layouts'
  messages:
    system-messages-3155: 'System Messages'
  logo:
    logo-4875: Logo
  menu:
    menu-8526: Menu
  shoppingcart:
    shoppingcart-8041: 'Shopping Cart'
  simplemenu:
    simplemenu-8198: 'Bottom Menu'
  branding:
    branding-6220: Branding
  mobile-menu:
    mobile-menu-9929: Mobile-menu
inherit:
  default:
    top: top
    navigation: navigation
    header: header
    above: above
    showcase: showcase
    utility: utility
    feature: feature
    expanded: expanded
    extension: extension
    bottom: bottom
    footer: footer
    copyright: copyright
    offcanvas: offcanvas
    system-messages-3155: system-messages-9828
    logo-4875: logo-5992
    menu-8526: menu-4196
    shoppingcart-8041: shoppingcart-5200
    simplemenu-8198: simplemenu-6826
    branding-6220: branding-9192
    mobile-menu-9929: mobile-menu-7951
