name: layouts_-_two_sidebars_left
timestamp: 1562905228
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1457353897
positions: {  }
sections:
  top: Top
  navigation: Navigation
  slideshow: Slideshow
  above: Above
  showcase: Showcase
  utility: Utility
  feature: Feature
  sidebar: Sidebar
  mainbar: Mainbar
  expanded: Expanded
  extension: Extension
  bottom: Bottom
  copyright: Copyright
  header: Header
  aside: Aside
  footer: Footer
  offcanvas: Offcanvas
particles:
  simplecontent:
    simplecontent-7561: 'Two Sidebars Left Example'
  custom:
    custom-7406: 'Left Sidebar'
    custom-6562: 'Custom HTML'
    custom-9224: 'Right Sidebar'
    custom-8235: 'H2 Heading'
  messages:
    system-messages-5632: 'System Messages'
  logo:
    logo-2209: Logo
  menu:
    menu-9470: Menu
  shoppingcart:
    shoppingcart-1797: 'Shopping Cart'
  simplemenu:
    simplemenu-2439: 'Bottom Menu'
  branding:
    branding-3261: Branding
  mobile-menu:
    mobile-menu-5802: Mobile-menu
inherit:
  default:
    top: top
    navigation: navigation
    header: header
    above: above
    showcase: showcase
    utility: utility
    feature: feature
    expanded: expanded
    extension: extension
    bottom: bottom
    footer: footer
    copyright: copyright
    offcanvas: offcanvas
    system-messages-5632: system-messages-9828
    logo-2209: logo-5992
    menu-9470: menu-4196
    shoppingcart-1797: shoppingcart-5200
    simplemenu-2439: simplemenu-6826
    branding-3261: branding-9192
    mobile-menu-5802: mobile-menu-7951
