name: _error
timestamp: 1582966292
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: _error
  timestamp: 1582965243
positions: {  }
sections:
  top: Top
  navigation: Navigation
  slideshow: Slideshow
  above: Above
  showcase: Showcase
  utility: Utility
  feature: Feature
  sidebar: Sidebar
  mainbar: Mainbar
  expanded: Expanded
  extension: Extension
  bottom: Bottom
  copyright: Copyright
  header: Header
  aside: Aside
  footer: Footer
  offcanvas: Offcanvas
particles:
  messages:
    system-messages-9828: 'System Messages'
  logo:
    logo-6939: Logo
  menu:
    menu-5286: Menu
  simplecontent:
    simplecontent-7561: 'We are sorry!'
    simplecontent-1811: 'Error Page Description'
  content:
    system-content-3192: 'Page Content'
  simplemenu:
    simplemenu-2419: 'Bottom Menu'
  branding:
    branding-5949: Branding
  mobile-menu:
    mobile-menu-5864: Mobile-menu
inherit:
  default:
    navigation: navigation
    logo-6939: logo-5992
    menu-5286: menu-4196
    copyright: copyright
    offcanvas: offcanvas
    simplemenu-2419: simplemenu-6826
    branding-5949: branding-9192
    mobile-menu-5864: mobile-menu-7951
