name: pages_-_portfolio
timestamp: 1583044113
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1478643075
positions:
  sidebar: Sidebar
  aside: Aside
sections:
  top: Top
  navigation: Navigation
  slideshow: Slideshow
  above: Above
  showcase: Showcase
  utility: Utility
  feature: Feature
  expanded: Expanded
  extension: Extension
  bottom: Bottom
  copyright: Copyright
  header: Header
  sidebar: Sidebar
  aside: Aside
  mainbar: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  simplecontent:
    simplecontent-5734: 'Header - Portfolio'
  infolist:
    infolist-8294: 'Portfolio Info List'
    infolist-4556: 'Portfolio Info List 2'
  imagegrid:
    imagegrid-3278: 'Portfolio Image Grid'
  messages:
    system-messages-8409: 'System Messages'
  logo:
    logo-8663: Logo
  menu:
    menu-5572: Menu
  shoppingcart:
    shoppingcart-4672: 'Shopping Cart'
  position:
    position-position-2095: Sidebar
    position-position-8368: Aside
  simplemenu:
    simplemenu-1972: 'Bottom Menu'
  branding:
    branding-7282: Branding
  mobile-menu:
    mobile-menu-5508: Mobile-menu
inherit:
  default:
    top: top
    navigation: navigation
    sidebar: sidebar
    aside: aside
    copyright: copyright
    offcanvas: offcanvas
    system-messages-8409: system-messages-9828
    logo-8663: logo-5992
    menu-5572: menu-4196
    shoppingcart-4672: shoppingcart-5200
    position-position-2095: position-position-8538
    position-position-8368: position-position-8807
    simplemenu-1972: simplemenu-6826
    branding-7282: branding-9192
    mobile-menu-5508: mobile-menu-7951
