name: features_-_particles
timestamp: 1583045663
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1477473229
positions: {  }
sections:
  top: Top
  navigation: Navigation
  slideshow: Slideshow
  above: Above
  feature: Feature
  expanded: Expanded
  extension: Extension
  bottom: Bottom
  copyright: Copyright
  header: Header
  footer: Footer
  offcanvas: Offcanvas
particles:
  simplecontent:
    simplecontent-6795: 'Particle - Owl Showcase'
    simplecontent-4973: 'Particle - Product List'
    simplecontent-3597: 'Particle - Infolist'
    simplecontent-7518: 'Particle - Owl Preview'
  owlshowcase:
    owlshowcase-6305: 'Owl Showcase'
  productlist:
    productlist-5988: 'Product List'
  infolist:
    infolist-4926: 'Info List'
  owlpreview:
    owlpreview-1172: 'Owl Preview'
  messages:
    system-messages-6984: 'System Messages'
  logo:
    logo-9153: Logo
  menu:
    menu-9777: Menu
  shoppingcart:
    shoppingcart-4498: 'Shopping Cart'
  simplemenu:
    simplemenu-9269: 'Bottom Menu'
  branding:
    branding-2395: Branding
  mobile-menu:
    mobile-menu-2039: Mobile-menu
inherit:
  default:
    top: top
    navigation: navigation
    copyright: copyright
    offcanvas: offcanvas
    system-messages-6984: system-messages-9828
    logo-9153: logo-5992
    menu-9777: menu-4196
    shoppingcart-4498: shoppingcart-5200
    simplemenu-9269: simplemenu-6826
    branding-2395: branding-9192
    mobile-menu-2039: mobile-menu-7951
  home_-_particles:
    slideshow: slideshow
    owlshowcase-6305: owlshowcase-7890
    header: header
    productlist-5988: productlist-8300
    above: above
    infolist-4926: infolist-3806
    feature: feature
    owlpreview-1172: owlpreview-1055
