ordering:
  home: ''
  features:
    overview: ''
    particles: ''
    typography: ''
    block-variations: ''
    documentation: ''
    forum-support: ''
    download: ''
  pages:
    -
      about-us: ''
      pricing: ''
      blog: ''
      portfolio: ''
    -
      contact: ''
      error: ''
      coming-soon: ''
      offline: ''
  layouts:
    full-width: ''
    left-sidebar: ''
    right-sidebar: ''
    two-sidebars: ''
    two-sidebars-left: ''
    two-sidebars-right: ''
    'Rows-&#038;-Columns': ''
  styles:
    __particle-lb4Ja: ''
items:
  home:
    object_id: 31
  features:
    object_id: 1
    dropdown_dir: right
    dropdown_hide: '0'
    width: 220px
  features/overview:
    object_id: 34
  features/particles:
    object_id: 81
  features/typography:
    object_id: 35
  features/block-variations:
    object_id: 36
  features/documentation:
    object_id: 2
  features/forum-support:
    object_id: 3
  features/download:
    object_id: 8
  pages:
    object_id: 4
    dropdown: fullwidth
    dropdown_dir: right
    dropdown_hide: '0'
    width: 320px
    columns:
      - 50
      - 50
  pages/about-us:
    object_id: 37
  pages/pricing:
    object_id: 38
  pages/blog:
    object_id: 22
  pages/portfolio:
    object_id: 39
  pages/contact:
    object_id: 40
  pages/error:
    object_id: 5
  pages/coming-soon:
    object_id: 50
  pages/offline:
    object_id: 51
  layouts:
    object_id: 7
    width: 200px
  layouts/full-width:
    object_id: 115
  layouts/left-sidebar:
    object_id: 118
  layouts/right-sidebar:
    object_id: 119
  layouts/two-sidebars:
    object_id: 121
  layouts/two-sidebars-left:
    object_id: 123
  layouts/two-sidebars-right:
    object_id: 125
  'layouts/Rows-&#038;-Columns':
    object_id: 127
  styles:
    object_id: 6
    dropdown: standard
    dropdown_dir: left
    dropdown_hide: '1'
    width: 35rem
    columns:
      - 100
  styles/__particle-lb4Ja:
    type: particle
    particle: custom
    title: 'Custom HTML'
    options:
      particle:
        enabled: '1'
        html: "<div class=\"g-grid g-preset-thumbnails center\">\n    <div class=\"g-block\">\n        <div class=\"g-content\">\n            <a href=\"?presets=preset1\">\n                <img src=\"gantry-media://rocketlauncher/styles/preset1.jpg\" alt=\"Preset 1\">\n                <br>\n                <span>Preset 1</span>\n            </a>\n        </div>\n    </div>\n    <div class=\"g-block\">\n        <div class=\"g-content\">\n            <a href=\"?presets=preset2\">\n                <img src=\"gantry-media://rocketlauncher/styles/preset2.jpg\" alt=\"Preset 2\">\n                <br>\n                <span>Preset 2</span>\n            </a>\n        </div>\n    </div>\n    <div class=\"g-block\">\n        <div class=\"g-content\">\n            <a href=\"?presets=preset3\">\n                <img src=\"gantry-media://rocketlauncher/styles/preset3.jpg\" alt=\"Preset 3\">\n                <br>\n                <span>Preset 3</span>\n            </a>\n        </div>\n    </div>\n    <div class=\"g-block\">\n        <div class=\"g-content\">\n            <a href=\"?presets=preset4\">\n                <img src=\"gantry-media://rocketlauncher/styles/preset4.jpg\" alt=\"Preset 4\">\n                <br>\n                <span>Preset 4</span>\n            </a>\n        </div>\n    </div>\n    <div class=\"g-block\">\n        <div class=\"g-content\">\n            <a href=\"?presets=preset5\">\n                <img src=\"gantry-media://rocketlauncher/styles/preset5.jpg\" alt=\"Preset 5\">\n                <br>\n                <span>Preset 5</span>\n            </a>\n        </div>\n    </div>\n <div class=\"g-block\">\n        <div class=\"g-content\">\n            <a href=\"?presets=preset6\">\n                <img src=\"gantry-media://rocketlauncher/styles/preset6.jpg\" alt=\"Preset 6\">\n                <br>\n                <span>Preset 6</span>\n            </a>\n        </div>\n    </div>\n\n</div>"
      block:
        extra: {  }
