name: features_-_block_variations
timestamp: 1562905228
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1478643075
positions:
  sidebar: Sidebar
  aside: Aside
sections:
  top: Top
  navigation: Navigation
  slideshow: Slideshow
  above: Above
  showcase: Showcase
  utility: Utility
  feature: Feature
  expanded: Expanded
  extension: Extension
  bottom: Bottom
  copyright: Copyright
  header: Header
  sidebar: Sidebar
  aside: Aside
  mainbar: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  simplecontent:
    simplecontent-6092: 'Header - Block Variations'
  content:
    system-content-1120: 'Page Content'
  custom:
    custom-5266: 'Block Variations - Additional Classes Header'
  infolist:
    infolist-1558: 'Block Variations - Additional Classes List'
  messages:
    system-messages-6150: 'System Messages'
  logo:
    logo-8878: Logo
  menu:
    menu-6430: Menu
  shoppingcart:
    shoppingcart-5394: 'Shopping Cart'
  position:
    position-position-8085: Sidebar
    position-position-9540: Aside
  simplemenu:
    simplemenu-5842: 'Bottom Menu'
  branding:
    branding-6622: Branding
  mobile-menu:
    mobile-menu-5873: Mobile-menu
inherit:
  default:
    top: top
    navigation: navigation
    sidebar: sidebar
    aside: aside
    copyright: copyright
    offcanvas: offcanvas
    system-messages-6150: system-messages-9828
    logo-8878: logo-5992
    menu-6430: menu-4196
    shoppingcart-5394: shoppingcart-5200
    position-position-8085: position-position-8538
    position-position-9540: position-position-8807
    simplemenu-5842: simplemenu-6826
    branding-6622: branding-9192
    mobile-menu-5873: mobile-menu-7951
