version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1478643075
layout:
  top: {  }
  navigation: {  }
  /slideshow/:
    -
      - simplecontent-6092
  /header/: {  }
  /above/: {  }
  /showcase/: {  }
  /utility/: {  }
  /feature/: {  }
  /container-main/:
    -
      -
        'sidebar 20': {  }
      -
        'mainbar 60':
          -
            - system-content-1120
      -
        'aside 20': {  }
  /expanded/: {  }
  /extension/: {  }
  /bottom/:
    -
      - custom-5266
    -
      - infolist-1558
  /footer/: {  }
  copyright: {  }
  offcanvas: {  }
structure:
  top:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  navigation:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  slideshow:
    type: section
    attributes:
      boxed: '3'
      class: ''
  header:
    attributes:
      boxed: '3'
      class: ''
  above:
    type: section
    attributes:
      boxed: '3'
      class: ''
  showcase:
    type: section
    attributes:
      boxed: '3'
      class: ''
  utility:
    type: section
    attributes:
      boxed: '3'
      class: ''
  feature:
    type: section
    attributes:
      boxed: '3'
      class: ''
  sidebar:
    type: section
    subtype: aside
    inherit:
      outline: default
      include:
        - attributes
        - children
        - block
  mainbar:
    type: section
    subtype: main
    title: Main
    attributes:
      class: ''
  aside:
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  container-main:
    attributes:
      boxed: '3'
      class: ''
      extra: {  }
  expanded:
    type: section
    attributes:
      boxed: '3'
      class: ''
  extension:
    type: section
    attributes:
      boxed: '3'
      class: ''
  bottom:
    type: section
    attributes:
      boxed: '3'
      class: ''
  footer:
    attributes:
      boxed: '3'
      class: ''
  copyright:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  offcanvas:
    inherit:
      outline: default
      include:
        - attributes
        - children
content:
  simplecontent-6092:
    title: 'Header - Block Variations'
    attributes:
      class: ''
      title: ''
      items:
        -
          layout: header
          created_date: ''
          content_title: 'Block Variations'
          author: ''
          leading_content: ''
          main_content: ''
          readmore_label: ''
          readmore_link: ''
          readmore_class: ''
          readmore_target: _self
          title: 'Block Variations'
  custom-5266:
    title: 'Block Variations - Additional Classes Header'
    attributes:
      html: "<h3 class=\"g-title\">Additional Effects & Classes</h3>\n<p>A collection of additional variations for structural and subtle stylistic adjustments.\nEffects and classes should be applied to the block within the Layout Manager, rather than in the module parameters, to ensure the desired effect is achieved.</p>"
    block:
      class: center
  infolist-1558:
    title: 'Block Variations - Additional Classes List'
    attributes:
      class: ''
      title: ''
      intro: ''
      cols: g-3cols
      infolists:
        -
          icon: ''
          iconloc: left
          image: ''
          imageloc: left
          textstyle: compact
          imagestyle: compact
          desc: 'Add low opacity to a block'
          tag: ''
          subtag: ''
          label: ''
          link: ''
          buttonicon: ''
          readmoreclass: ''
          readmoretarget: _self
          title: Disabled
        -
          icon: ''
          iconloc: left
          image: ''
          imageloc: left
          textstyle: compact
          imagestyle: compact
          desc: 'Center the block content'
          tag: ''
          subtag: ''
          label: ''
          link: ''
          buttonicon: ''
          readmoreclass: ''
          readmoretarget: _self
          title: Center
        -
          icon: ''
          iconloc: left
          image: ''
          imageloc: left
          textstyle: compact
          imagestyle: compact
          desc: 'Apply background to the whole block'
          tag: ''
          subtag: ''
          label: ''
          link: ''
          buttonicon: ''
          readmoreclass: ''
          readmoretarget: _self
          title: 'Outer Box'
        -
          icon: ''
          iconloc: left
          image: ''
          imageloc: left
          textstyle: compact
          imagestyle: compact
          desc: 'Remove outer margin/padding'
          tag: ''
          subtag: ''
          label: ''
          link: ''
          buttonicon: ''
          readmoreclass: ''
          readmoretarget: _self
          title: Flush
        -
          icon: ''
          iconloc: left
          image: ''
          imageloc: left
          textstyle: compact
          imagestyle: compact
          desc: 'Align block content to the left'
          tag: ''
          subtag: ''
          label: ''
          link: ''
          buttonicon: ''
          readmoreclass: ''
          readmoretarget: _self
          title: 'Align Left'
        -
          icon: ''
          iconloc: left
          image: ''
          imageloc: left
          textstyle: compact
          imagestyle: compact
          desc: 'Align block content to the right'
          tag: ''
          subtag: ''
          label: ''
          link: ''
          buttonicon: ''
          readmoreclass: ''
          readmoretarget: _self
          title: 'Align Right'
        -
          icon: ''
          iconloc: left
          image: ''
          imageloc: left
          textstyle: compact
          imagestyle: compact
          desc: 'Remove outer margin'
          tag: ''
          subtag: ''
          label: ''
          link: ''
          buttonicon: ''
          readmoreclass: ''
          readmoretarget: _self
          title: 'No Margin'
        -
          icon: ''
          iconloc: left
          image: ''
          imageloc: left
          textstyle: compact
          imagestyle: compact
          desc: 'Remove outer padding'
          tag: ''
          subtag: ''
          label: ''
          link: ''
          buttonicon: ''
          readmoreclass: ''
          readmoretarget: _self
          title: 'No Padding'
        -
          icon: ''
          iconloc: left
          image: ''
          imageloc: left
          textstyle: compact
          imagestyle: compact
          desc: 'Add squared corners to a block'
          tag: ''
          subtag: ''
          label: ''
          link: ''
          buttonicon: ''
          readmoreclass: ''
          readmoretarget: _self
          title: Square
        -
          icon: ''
          iconloc: left
          image: ''
          imageloc: left
          textstyle: compact
          imagestyle: compact
          desc: 'Add rounded corners to a block'
          tag: ''
          subtag: ''
          label: ''
          link: ''
          buttonicon: ''
          readmoreclass: ''
          readmoretarget: _self
          title: Rounded
        -
          icon: ''
          iconloc: left
          image: ''
          imageloc: left
          textstyle: compact
          imagestyle: compact
          desc: 'Add a shadow effect to a block'
          tag: ''
          subtag: ''
          label: ''
          link: ''
          buttonicon: ''
          readmoreclass: ''
          readmoretarget: _self
          title: 'Shadow 1'
        -
          icon: ''
          iconloc: left
          image: ''
          imageloc: left
          textstyle: compact
          imagestyle: compact
          desc: 'Add a shadow effect to a block'
          tag: ''
          subtag: ''
          label: ''
          link: ''
          buttonicon: ''
          readmoreclass: ''
          readmoretarget: _self
          title: 'Shadow 2'
    block:
      class: center
