name: pages_-_about_us
timestamp: 1562905228
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1478643075
positions:
  sidebar: Sidebar
  aside: Aside
sections:
  top: Top
  navigation: Navigation
  slideshow: Slideshow
  above: Above
  showcase: Showcase
  utility: Utility
  feature: Feature
  expanded: Expanded
  extension: Extension
  bottom: Bottom
  copyright: Copyright
  header: Header
  sidebar: Sidebar
  aside: Aside
  mainbar: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  simplecontent:
    simplecontent-2958: 'Header - About Us'
  blockcontent:
    blockcontent-4951: 'About Us - Who we are'
    blockcontent-7411: 'About Us - What we do'
  messages:
    system-messages-4747: 'System Messages'
  logo:
    logo-2581: Logo
  menu:
    menu-8080: Menu
  shoppingcart:
    shoppingcart-8369: 'Shopping Cart'
  position:
    position-position-5607: Sidebar
    position-position-8641: Aside
  simplemenu:
    simplemenu-3773: 'Bottom Menu'
  branding:
    branding-2321: Branding
  mobile-menu:
    mobile-menu-4041: Mobile-menu
inherit:
  default:
    top: top
    navigation: navigation
    sidebar: sidebar
    aside: aside
    copyright: copyright
    offcanvas: offcanvas
    system-messages-4747: system-messages-9828
    logo-2581: logo-5992
    menu-8080: menu-4196
    shoppingcart-8369: shoppingcart-5200
    position-position-5607: position-position-8538
    position-position-8641: position-position-8807
    simplemenu-3773: simplemenu-6826
    branding-2321: branding-9192
    mobile-menu-4041: mobile-menu-7951
