name: pages_-_blog
timestamp: 1583046185
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1478643075
positions:
  sidebar: Sidebar
  aside: Aside
sections:
  top: Top
  navigation: Navigation
  slideshow: Slideshow
  above: Above
  showcase: Showcase
  utility: Utility
  feature: Feature
  expanded: Expanded
  extension: Extension
  bottom: Bottom
  copyright: Copyright
  header: Header
  sidebar: Sidebar
  aside: Aside
  mainbar: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  messages:
    system-messages-9509: 'System Messages'
  logo:
    logo-3746: Logo
  menu:
    menu-8045: Menu
  shoppingcart:
    shoppingcart-8092: 'Shopping Cart'
  simplecontent:
    simplecontent-4298: 'Header - Blog'
  position:
    position-position-2240: Sidebar
    position-position-3988: Aside
  content:
    system-content-1120: 'Page Content'
  simplemenu:
    simplemenu-7055: 'Bottom Menu'
  branding:
    branding-5725: Branding
  mobile-menu:
    mobile-menu-1771: Mobile-menu
inherit:
  default:
    top: top
    system-messages-9509: system-messages-9828
    navigation: navigation
    logo-3746: logo-5992
    menu-8045: menu-4196
    shoppingcart-8092: shoppingcart-5200
    sidebar: sidebar
    position-position-2240: position-position-8538
    aside: aside
    position-position-3988: position-position-8807
    copyright: copyright
    simplemenu-7055: simplemenu-6826
    branding-5725: branding-9192
    offcanvas: offcanvas
    mobile-menu-1771: mobile-menu-7951
