version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1478643075
layout:
  top: {  }
  navigation: {  }
  /slideshow/:
    -
      - simplecontent-2045
  /header/: {  }
  /above/: {  }
  /showcase/: {  }
  /utility/: {  }
  /feature/: {  }
  /container-main/:
    -
      -
        'sidebar 20': {  }
      -
        'mainbar 60':
          -
            - system-content-1120
      -
        'aside 20': {  }
  /expanded/: {  }
  /extension/:
    -
      - custom-5214
  /bottom/: {  }
  /footer/: {  }
  copyright: {  }
  offcanvas: {  }
structure:
  top:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  navigation:
    type: section
    inherit:
      outline: default
      include:
        - children
        - attributes
  slideshow:
    type: section
    attributes:
      boxed: '3'
      class: ''
  header:
    attributes:
      boxed: '3'
      class: ''
  above:
    type: section
    attributes:
      boxed: '3'
      class: ''
  showcase:
    type: section
    attributes:
      boxed: '3'
      class: ''
  utility:
    type: section
    attributes:
      boxed: '3'
      class: ''
  feature:
    type: section
    attributes:
      boxed: '3'
      class: ''
  sidebar:
    type: section
    subtype: aside
    inherit:
      outline: default
      include:
        - block
        - children
        - attributes
  mainbar:
    type: section
    subtype: main
    title: Main
    attributes:
      class: ''
  aside:
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  container-main:
    attributes:
      boxed: '3'
      class: ''
      extra: {  }
  expanded:
    type: section
    attributes:
      boxed: '3'
      class: ''
  extension:
    type: section
    attributes:
      boxed: '3'
      class: ''
  bottom:
    type: section
    attributes:
      boxed: '3'
      class: ''
  footer:
    attributes:
      boxed: '3'
      class: ''
  copyright:
    type: section
    inherit:
      outline: default
      include:
        - children
        - attributes
  offcanvas:
    inherit:
      outline: default
      include:
        - children
        - attributes
content:
  simplecontent-2045:
    title: 'Header - Offline'
    attributes:
      class: ''
      title: ''
      items:
        -
          layout: header
          created_date: ''
          content_title: 'Offline Page'
          author: ''
          leading_content: ''
          main_content: ''
          readmore_label: ''
          readmore_link: ''
          readmore_class: ''
          readmore_target: _self
          title: Offline
  custom-5214:
    title: 'Make your WordPress offline'
    attributes:
      html: "<p>To make your WordPress website unavailable to visitors, replacing it with a simple message, do this:</p>\n\n<ol>\n  <li> Log in to the Administrator dashboard.</li>\n  <li> Click on the <strong>Theme Settings</strong> button in the admin sidebar.</li>\n  <li> Click in the top right corner on the <strong>Extras</strong> button and select <strong>Platform Settings</strong>.</li>\n  <li> Find where it says <strong>Offline Mode</strong> and select the <strong>Enabled</strong> radio button.</li>\n  <li><strong>Optional:</strong> Change the <strong>Offline Message</strong> to give your visitors some explanation about why your website is unavailable.</li>\n  <li> Click the <strong>Save Changes</strong> button to implement the new settings.</li>\n  <li>You should see a message confirming the settings have been changed.</li>\n</ol>"
