name: layouts_-_rows_columns
timestamp: 1583044113
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1457353897
positions: {  }
sections:
  top: Top
  navigation: Navigation
  slideshow: Slideshow
  above: Above
  showcase: Showcase
  utility: Utility
  feature: Feature
  sidebar: Sidebar
  mainbar: Mainbar
  expanded: Expanded
  extension: Extension
  bottom: Bottom
  copyright: Copyright
  header: Header
  aside: Aside
  footer: Footer
  offcanvas: Offcanvas
particles:
  simplecontent:
    simplecontent-7561: 'Rows & Columns Example'
  custom:
    custom-2875: 'Equal Width Examples'
    custom-4860: 'Single Block per Row'
    custom-9868: 'Two Blocks per Row'
    custom-4807: 'Two Blocks per Row'
    custom-3780: 'Three Blocks per Row'
    custom-7528: 'Three Blocks per Row'
    custom-3751: 'Three Blocks per Row'
    custom-6453: 'Four Blocks per Row'
    custom-6496: 'Four Blocks per Row'
    custom-3872: 'Four Blocks per Row'
    custom-9371: 'Four Blocks per Row'
    custom-9988: 'Different Width Examples'
    custom-4289: '25% Width Block'
    custom-1256: '75% Width Block'
    custom-2720: '25% Width Block'
    custom-5527: '26% Width Block'
    custom-1752: '31% Width Block'
    custom-4132: '43% Width Block'
    custom-5410: 'Mainbody Examples'
    custom-6468: 'Custom HTML'
    custom-4397: 'Custom HTML'
    custom-8735: 'Custom HTML'
    custom-5316: 'Custom HTML'
    custom-9449: 'Custom HTML'
    custom-6027: 'Custom HTML'
    custom-2369: 'Custom HTML'
    custom-2507: 'Custom HTML'
    custom-2846: 'Custom HTML'
  messages:
    system-messages-2258: 'System Messages'
  logo:
    logo-9370: Logo
  menu:
    menu-3359: Menu
  shoppingcart:
    shoppingcart-5999: 'Shopping Cart'
  simplemenu:
    simplemenu-1973: 'Bottom Menu'
  branding:
    branding-7220: Branding
  mobile-menu:
    mobile-menu-8408: Mobile-menu
inherit:
  default:
    top: top
    navigation: navigation
    header: header
    showcase: showcase
    utility: utility
    feature: feature
    expanded: expanded
    extension: extension
    bottom: bottom
    footer: footer
    copyright: copyright
    offcanvas: offcanvas
    system-messages-2258: system-messages-9828
    logo-9370: logo-5992
    menu-3359: menu-4196
    shoppingcart-5999: shoppingcart-5200
    simplemenu-1973: simplemenu-6826
    branding-7220: branding-9192
    mobile-menu-8408: mobile-menu-7951
