name: home_-_particles
timestamp: 1562905228
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1478287635
positions: {  }
sections:
  top: Top
  navigation: Navigation
  slideshow: Slideshow
  above: Above
  feature: Feature
  expanded: Expanded
  extension: Extension
  bottom: Bottom
  copyright: Copyright
  header: Header
  footer: Footer
  offcanvas: Offcanvas
particles:
  simplecontent:
    simplecontent-7077: 'Simple Content'
    simplecontent-6429: 'Simple Content'
    simplecontent-9567: 'Get the latest product updates in your inbox!'
  owlshowcase:
    owlshowcase-7890: 'Owl Showcase'
  productlist:
    productlist-8300: 'Product List'
  infolist:
    infolist-3806: 'Info List'
  owlpreview:
    owlpreview-1055: 'Owl Preview'
  custom:
    custom-5911: 'Custom HTML'
  newsletter:
    newsletter-3789: Newsletter
  messages:
    system-messages-2483: 'System Messages'
  logo:
    logo-5641: Logo
  menu:
    menu-5403: Menu
  shoppingcart:
    shoppingcart-9275: 'Shopping Cart'
  simplemenu:
    simplemenu-9153: 'Bottom Menu'
  branding:
    branding-8834: Branding
  mobile-menu:
    mobile-menu-5317: Mobile-menu
inherit:
  default:
    top: top
    navigation: navigation
    copyright: copyright
    offcanvas: offcanvas
    system-messages-2483: system-messages-9828
    logo-5641: logo-5992
    menu-5403: menu-4196
    shoppingcart-9275: shoppingcart-5200
    simplemenu-9153: simplemenu-6826
    branding-8834: branding-9192
    mobile-menu-5317: mobile-menu-7951
